---
title: "bayes-2-project"
author: "Jennifer Chen, Qier Meng"
date: "5/17/2021"
output: html_document
---

```{r}
library(rjags)
library(coda)
library(lmtest)
library(pROC)
library(dplyr)
library(tidyverse)
```

## Data

```{r}
load('./nmes.rdata')

# remove incomplete cases
nmes <- nmes[nmes$eversmk!='.',]
nmes <- nmes[nmes$male!='.',]
nmes <- nmes[nmes$lastage!='.',]

# define mscd
nmes$mscd <- ifelse(nmes$lc5==1 | nmes$chd5==1, 1, 0)
nmes$eversmk <- as.integer(nmes$eversmk)
nmes$age <- nmes$lastage

head(nmes[c("mscd","eversmk", "male", "age")])

# mscd vs. eversmk
t <- table(nmes$mscd, nmes$eversmk)
colnames(t) <- c("Never smoked", "Smoked")
rownames(t) <- c("No MSCD", "MSCD")
t

t <- table(nmes$mscd, nmes$male)
colnames(t) <- c("Female", "Male")
rownames(t) <- c("No MSCD", "MSCD")
t
```

## Model

$$
\begin{align*}
[\text{MSCD}_i | \text{eversmk}_i, \text{male}_i, \text{age}_i, \alpha, \beta, \gamma] &\sim \text{Bernoulli}(\theta_i)\\
\text{logit}(\theta_i) &= \alpha + \beta_1 \gamma_1 \text{eversmk}_i + \beta_2 \gamma_2 \text{male}_i + \beta_3 \gamma_3 \text{age}_i\\
\alpha &\sim \text{Normal}(0, 10)\\
\beta_j &\sim \text{Normal}(0, 2) ~~ j=1,2,3\\
\gamma_j &\sim \text{Bernoulli}(0.5).
\end{align*}
$$

## Implementation

```{r}
# split data into training set and test set
set.seed(0)
idx <- sample(nrow(nmes), 11684, replace=FALSE)
train.dat <- nmes[idx[1:10000],]
test.dat <- nmes[idx[10001:11684],]
```

```{r}
# bayesian model

dat <- list(y = train.dat$mscd, 
            x1 = train.dat$eversmk,
            x2 = train.dat$male,
            x3 = (train.dat$age - mean(train.dat$age)) / sd(train.dat$age),
            n = 10000)

modelstring="model {
  alpha ~ dnorm(0, 1/100)
  for (j in 1:3){
    beta[j] ~ dnorm(0, 1/4)
    gamma[j] ~ dbern(0.5)
  }
  for (i in 1:n) {
    logit( theta[i] ) <- alpha + beta[1]*gamma[1]*x1[i] + beta[2]*gamma[2]*x2[i] + beta[3]*gamma[3]*x3[i]
    y[i] ~ dbern(theta[i])
  }
}"

model <- jags.model(textConnection(modelstring), data=dat)
```

```{r}
update(model, n.iter=1000)
output <- coda.samples(model=model,
                       variable.names=c("alpha", "beta", "gamma"),
                       n.iter=2000,
                       thin=1)
```

```{r}
n.chains <- 1
n.iter <- 2000
betas <- output %>%
    map_dfr(as_tibble) %>%
    mutate(chain=rep(paste("Chain", seq_len(n.chains)),
                     each=n.iter),
           iter=rep(seq_len(n.iter), n.chains))

gamma.post <- as.data.frame(as.matrix(betas[,5:7]))
gamma.string <- as.data.frame(apply(gamma.post, MARGIN=1, FUN=toString))
table(gamma.string)
```
$$
\gamma_j \sim \text{Bernuolli}(0.5), j=1,2,3 \\
P(\gamma_1=1| \pmb{x}, \pmb{y}) = 1 \\
P(\gamma_2=1| \pmb{x}, \pmb{y}) = 0.4465 \\ # may change this according to model output
P(\gamma_3=1| \pmb{x}, \pmb{y}) = 1 \\
$$

## Prediction

```{r}
Xtest <- model.matrix(mscd ~ eversmk + age + male, data=test.dat)
B <- as.matrix(betas[, 1:4])
pred <- Xtest %*% t(B)
m <- tibble(model_average=rowMeans(pred),
            mscd=test.dat$mscd)
p <- pROC::roc(m$mscd, m$model_average, ci=TRUE)
```
```{r}
plot(p)
p$auc
```

## Frequentist approach

```{r}
lr <- glm(mscd ~ eversmk + male + age, data=train.dat, family=binomial(link="logit"))
summary.glm(lr)$coefficients

test.dat$pred <- predict(lr, newdata=test.dat, type = "response")
```

```{r}
ROC <- roc(test.dat$mscd, test.dat$pred)

plot(1 - ROC$specificities, ROC$sensitivities,
xlim = c(0, 1), ylim = c(0, 1), xlab = "", ylab = "",
pch = 16, col = "black", cex = 0.8, type = "l")
abline(c(0, 1), col = "grey", lty = 2)
title(xlab = "1-specificity", line = 1.9)
title(ylab = "sensitivity", line = 1.9)

ROC$auc
```

$$
\begin{align*}
[\text{MSCD}_i | \text{eversmk}_i, \text{male}_i, \text{age}_i, \alpha, \beta, \gamma] &\sim \text{Bernoulli}(\theta_i)\\
\text{logit}(\theta_i) &= \alpha + \beta_1 \gamma_1 \text{eversmk}_i + \beta_2 \gamma_2 \text{male}_i + \beta_3 \gamma_3 \text{age}_i\\
\alpha &\sim \text{Normal}(-6.84, 0.21)\\
\beta_1 &\sim \text{Normal}(0.71, 0.074) \\
\beta_2 &\sim \text{Normal}(0.07, 0.003) \\
\beta_3 &\sim \text{Normal}(0.17, 0.069) \\
\gamma_j &\sim \text{Bernoulli}(0.5).
\end{align*}
$$

```{r}
# bayesian model

# center
dat <- list(y = train.dat$mscd, 
            x1 = train.dat$eversmk,
            x2 = train.dat$male,
            x3 = (train.dat$age - mean(train.dat$age)) / sd(train.dat$age),
            n = 10000)

modelstring2="model {
  alpha ~ dnorm(-6.84, 1/0.0441)
  beta[1] ~ dnorm(0.71, 1/0.005476)
  beta[2] ~ dnorm(0.07, 1/0.000009)
  beta[3] ~ dnorm(0.17, 1/0.004761)
  for (j in 1:3){
    gamma[j] ~ dbern(0.5)
  }
  for (i in 1:n) {
    logit( theta[i] ) <- alpha + beta[1]*gamma[1]*x1[i] + beta[2]*gamma[2]*x2[i] + beta[3]*gamma[3]*x3[i]
    y[i] ~ dbern(theta[i])
  }
}"

model2 <- jags.model(textConnection(modelstring2), data=dat)
```

```{r}
update(model2, n.iter=1000)
output2 <- coda.samples(model=model2,
                       variable.names=c("alpha", "beta", "gamma"),
                       n.iter=2000,
                       thin=1)
```

```{r}
betas2 <- output %>%
    map_dfr(as_tibble) %>%
    mutate(chain=rep(paste("Chain", seq_len(n.chains)),
                     each=n.iter),
           iter=rep(seq_len(n.iter), n.chains))

gamma.post2 <- as.data.frame(as.matrix(betas2[,5:7]))
gamma.string2 <- as.data.frame(apply(gamma.post2, MARGIN=1, FUN=toString))
table(gamma.string2)
```

$$
\gamma_j \sim \text{Bernuolli}(0.5), j=1,2,3 \\
P(\gamma_1=1| \pmb{x}, \pmb{y}) = 1 \\
P(\gamma_2=1| \pmb{x}, \pmb{y}) = 0.4465 \\ # may change this according to model output
P(\gamma_3=1| \pmb{x}, \pmb{y}) = 1 \\
$$

```{r}
Xtest <- model.matrix(mscd ~ eversmk + male + age,
                      data=test.dat)
B <- as.matrix(betas2[, 1:4])
pred <- Xtest %*% t(B)
m <- tibble(model_average=rowMeans(pred),
            mscd=test.dat$mscd)
p <- pROC::roc(m$mscd, m$model_average, ci=TRUE)
```

```{r}
plot(p)
p$auc
```